const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');const {URL}=require('url');const {Pool}=require('pg');
const PORT=process.env.PORT||10000,ROOT=__dirname,APP_ID='6a357c8d5553d30c6b90df5a';
if(!process.env.DATABASE_URL) { console.error('DATABASE_URL is required'); process.exit(1); }
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:false},max:5});
const uuid=()=>crypto.randomUUID();const hash=(p,s=crypto.randomBytes(16).toString('hex'))=>s+':'+crypto.pbkdf2Sync(String(p),s,120000,32,'sha256').toString('hex');
function check(p,h){const [s,v]=String(h||'').split(':');if(!s||!v)return false;const a=Buffer.from(v),b=Buffer.from(hash(p,s).split(':')[1]);return a.length===b.length&&crypto.timingSafeEqual(a,b)}
const pub=u=>{if(!u)return null;return {id:u.id,email:u.email,full_name:u.full_name||'',role:u.role,onboarding_completed:!!u.onboarding_completed,created_date:u.created_at,created_at:u.created_at,updated_date:u.updated_at}};
const secret=()=>process.env.AUTH_SECRET||'precocerto-change-auth-secret';
function sign(u){const p=Buffer.from(JSON.stringify({id:u.id,exp:Date.now()+7*864e5})).toString('base64url');return p+'.'+crypto.createHmac('sha256',secret()).update(p).digest('base64url')}
async function current(req){const t=(req.headers.authorization||'').replace(/^Bearer\s+/,'');const [p,s]=t.split('.');if(!p||!s)return null;try{const x=JSON.parse(Buffer.from(p,'base64url'));const sig=crypto.createHmac('sha256',secret()).update(p).digest('base64url');if(x.exp<Date.now()||sig!==s)return null;return (await pool.query('SELECT * FROM users WHERE id=$1',[x.id])).rows[0]||null}catch{return null}}
function json(res,status,data){res.writeHead(status,{'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','access-control-allow-headers':'authorization,content-type','access-control-allow-methods':'GET,POST,PUT,DELETE,OPTIONS'});res.end(JSON.stringify(data))}
async function body(req){const chunks=[];for await(const c of req)chunks.push(c);try{return JSON.parse(Buffer.concat(chunks).toString()||'{}')}catch{return {}}}
async function init(){const schema=fs.readFileSync(path.join(ROOT,'schema.sql'),'utf8');await pool.query(schema);const e='emilliamorim14@gmail.com';const r=await pool.query('SELECT id FROM users WHERE lower(email)=lower($1)',[e]);if(!r.rowCount)await pool.query('INSERT INTO users(email,full_name,password_hash,role) VALUES($1,$2,$3,$4)',[e,'Emillia Morim',''+hash(process.env.ADMIN_INITIAL_PASSWORD||'PcAdm-7vQ!29mL#'),'admin']);}
async function api(req,res){if(req.method==='OPTIONS')return json(res,204,{});const u=new URL(req.url,'http://localhost'),p=u.pathname,b=await body(req),me=await current(req);
 // The frontend performs this health/config request on every boot. Keep it local so
 // no Base44 public-settings call can block the auth state machine with a 404.
 if(req.method==='GET'&&/^\/api\/apps\/public\/[^/]+\/public-settings\/by-id\/[^/]+$/.test(p))return json(res,200,{app_id:APP_ID,enabled:true,environment:'production'});
 let m=p.match(/^\/api\/apps\/[^/]+\/auth\/(login|register)$/);
 if(m){if(m[1]==='login'){const q=await pool.query('SELECT * FROM users WHERE lower(email)=lower($1)',[String(b.email||'')]);const x=q.rows[0];if(!x||!check(b.password,x.password_hash))return json(res,401,{message:'E-mail ou senha inválidos'});return json(res,200,{access_token:sign(x),user:pub(x)})}if(!b.email||!b.password)return json(res,400,{message:'E-mail e senha são obrigatórios'});try{const q=await pool.query('INSERT INTO users(email,full_name,password_hash,role) VALUES(lower($1),$2,$3,$4) RETURNING *',[b.email,b.full_name||b.name||'',hash(b.password),'user']);const x=q.rows[0];return json(res,201,{access_token:sign(x),user:pub(x)})}catch(e){if(e.code==='23505')return json(res,409,{message:'E-mail já cadastrado'});throw e}}
 if(p.match(/^\/api\/apps\/[^/]+\/auth\/me$/)&&req.method==='GET')return me?json(res,200,pub(me)):json(res,401,{message:'Autenticação necessária'});
 if(!me){if(p.includes('/auth/logout'))return json(res,200,{ok:true});return json(res,401,{message:'Autenticação necessária'})}
 if(p.match(/\/entities\/User\/me$/)){if(req.method==='GET')return json(res,200,pub(me));if(req.method==='PUT'){const name=b.full_name??b.name??me.full_name;const onboarding=b.onboarding_completed===true||me.onboarding_completed===true;const q=await pool.query('UPDATE users SET full_name=$1,onboarding_completed=$2,updated_at=NOW() WHERE id=$3 RETURNING *',[name,onboarding,me.id]);return json(res,200,pub(q.rows[0]))}}
 if(/\/auth\/change(?:-password)?$/.test(p)&&req.method==='POST'){if(!check(b.current_password||b.old_password,me.password_hash)||!b.new_password)return json(res,400,{message:'Senha atual inválida ou nova senha ausente'});await pool.query('UPDATE users SET password_hash=$1,updated_at=NOW() WHERE id=$2',[hash(b.new_password),me.id]);return json(res,200,{ok:true})}
 let m2=p.match(/^\/api\/apps\/[^/]+\/entities\/([^/]+)(?:\/([^/]+))?$/);if(m2){const name=decodeURIComponent(m2[1]),id=m2[2];if(name==='User'){if(req.method==='GET'){if(me.role!=='admin')return json(res,403,{message:'Acesso restrito ao ADM'});const q=await pool.query('SELECT * FROM users ORDER BY created_at');return json(res,200,q.rows.map(pub))}if(req.method==='DELETE'&&id){if(id===me.id)return json(res,403,{message:'O ADM não pode excluir a própria conta'});if(me.role!=='admin')return json(res,403,{message:'Acesso restrito ao ADM'});await pool.query('DELETE FROM users WHERE id=$1',[id]);return json(res,200,{ok:true})}}
 if(req.method==='GET'&&!id){let q={};try{q=JSON.parse(u.searchParams.get('q')||'{}')}catch{};const rows=(await pool.query('SELECT * FROM entities WHERE entity_name=$1 AND created_by_id=$2 ORDER BY created_at',[name,me.id])).rows;return json(res,200,rows.filter(x=>Object.entries(q).every(([k,v])=>{if(k==='id')return String(x.id)===String(v);if(k==='created_by_id')return String(x.created_by_id)===String(v);if(k==='created_date'||k==='created_at')return String(x.created_at)===String(v);if(k==='updated_date'||k==='updated_at')return String(x.updated_at)===String(v);return x.data[k]===v})).map(x=>({...x.data,id:x.id,created_by_id:x.created_by_id,created_date:x.created_at,created_at:x.created_at,updated_date:x.updated_at})))}
 if(req.method==='POST'&&!id){const eid=uuid(),data={...b};delete data.id;delete data.created_by_id;delete data.created_date;delete data.created_at;delete data.updated_date;delete data.updated_at;const q=await pool.query('INSERT INTO entities(id,entity_name,created_by_id,data) VALUES($1,$2,$3,$4) RETURNING *',[eid,name,me.id,data]);return json(res,201,{...data,id:eid,created_by_id:me.id,created_date:q.rows[0].created_at,created_at:q.rows[0].created_at})}
 const q=await pool.query('SELECT * FROM entities WHERE id=$1 AND entity_name=$2 AND created_by_id=$3',[id,name,me.id]);if(!q.rowCount)return json(res,404,{message:'Registro não encontrado'});const x=q.rows[0];if(req.method==='GET')return json(res,200,{...x.data,id:x.id,created_by_id:x.created_by_id});if(req.method==='PUT'){const data={...x.data,...b};delete data.id;const z=await pool.query('UPDATE entities SET data=$1,updated_at=NOW() WHERE id=$2 RETURNING *',[data,id]);return json(res,200,{...data,id,created_by_id:me.id,updated_date:z.rows[0].updated_at})}if(req.method==='DELETE'){await pool.query('DELETE FROM entities WHERE id=$1',[id]);return json(res,200,{ok:true})}}
 if(p==='/api/account'&&req.method==='DELETE'){if(me.role==='admin'&&(await pool.query('SELECT count(*) FROM users')).rows[0].count>1)return json(res,403,{message:'O ADM não pode excluir a própria conta enquanto houver usuários'});await pool.query('DELETE FROM users WHERE id=$1',[me.id]);return json(res,200,{ok:true})}
 if(p==='/api/proportion'&&req.method==='POST'){const base=Number(b.base),target=Number(b.target);if(!isFinite(base)||!isFinite(target)||base<=0)return json(res,400,{message:'Valores inválidos'});return json(res,200,{factor:target/base,value:Number(b.value||0)*target/base})}return json(res,404,{message:'Rota não encontrada'})}
function mime(f){return ({'.html':'text/html; charset=utf-8','.js':'application/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml','.webmanifest':'application/manifest+json'})[path.extname(f).toLowerCase()]||'application/octet-stream'}
init().then(()=>http.createServer((req,res)=>{if(req.url.startsWith('/api/'))return api(req,res).catch(e=>{console.error(e);json(res,500,{message:'Erro interno'})});let p=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(p==='/'||!path.extname(p))p='/index.html';const f=path.join(ROOT,p);if(!f.startsWith(ROOT)||!fs.existsSync(f)||fs.statSync(f).isDirectory()){res.writeHead(404);return res.end('Not Found')}res.writeHead(200,{'content-type':mime(f),'cache-control':'no-cache'});fs.createReadStream(f).pipe(res)}).listen(PORT,'0.0.0.0',()=>console.log('Preço Certo listening on '+PORT))).catch(e=>{console.error('Database initialization failed',e);process.exit(1)});
